### ISSUE TITLE
 [Feature Request] Minimap Alpha Controls

### ISSUE THREAD

**Issue by gageracer** [joaoc-pires/wow-addon-conceal#10]
Hello, I would love to have minimap controls for alpha effects. I think the minimap is the only thing that occupies the biggest space when you want to have a minimal UI, and most of the time it is useless. Having control over it would be amazing.

**Comment by joaoc-pires** [comment]
This is something I want to have as well. There's a couple of problems I need to solve to have it work like the other elements but for sure a version of this will come in v1.5
