### ISSUE TITLE
[Feature Request] Only reveal in combat setting

### ISSUE THREAD

**Issue by Icarus-the-phoenix** [joaoc-pires/wow-addon-conceal#15]
Love the addon, but unfortunately it doesn't work well with action targeting. When action targeting is turned on, my bars are constantly fading in as the game automatically targets neutral and enemy units in front of my character.

Could we get a setting that allows us to ignore revealing bars when you have a target, and only reveal bars in combat instead? 

The setting be called something like:
Toggle: Fade based on Combat state
Toggle: Fade in with target
Toggle: Fade in only in Combat

**Comment by joaoc-pires** [comment]
This is implemented in version 2.1.0
In the Options, select Conceal, select Action Target Mode

Thanks for your interest, mate ;)

**Comment by Icarus-the-phoenix** [comment]
Wow! Didn't expect such a quick response! Thanks for the help :D
