### ISSUE TITLE
Keep QueueStatusButton visible

### ISSUE THREAD

**Issue by class2u** [joaoc-pires/wow-addon-conceal#3]
Hi, thank you for making this wonderful addon. I like it so much. I have a feature request. Could you please keep QueueStatusButton visible when MicroButtonAndBagsBar is hidden. Maybe add QueueStatusButton:SetParent(UIParent) to separate them will be fine.

**Comment by joaoc-pires** [comment]
Hey, I'll look into it.

**Comment by joaoc-pires** [comment]
Next release will contain this request
