### ISSUE TITLE
[Feature Request] Finer Controls

### ISSUE THREAD

**Issue by kirin6666** [joaoc-pires/wow-addon-conceal#4]
Hey! I have more of a feature request than anything really. Can you make the Fade options more modular? 
I'll give you an example of what I'm looking for - 
microbar faded until I mouseover, bags faded completely
AB 4/5 - completely faded until mouseover
Rest of AB - faded with option of 5 until combat.
Right now there's a way u can achieve the things that I want very closely but not quite as a lot of the stuff that I want perma hidden shows or keeps on showing cuz u can't quite have a fine control over it.
Do you think it's possible in the nearby future? Thanks in advance.

**Comment by joaoc-pires** [comment]
Hey
I do feel the settings are getting a bit too complicated already, but I'll see what I can do.

**Comment by kirin6666** [comment]
Does that men you gave up on implementing it?

**Comment by joaoc-pires** [comment]
Actually, no. I closed this by mistake. Ment to keep it open, sorry!

**Comment by joaoc-pires** [comment]
I'm sorry but I won't implement this. The settings are already as complicated as I feel confortable implementing.
