### ISSUE TITLE
[Feature Request] Toggleable Mouseover

### ISSUE THREAD

**Issue by Lunaeria** [joaoc-pires/wow-addon-conceal#6]
Would it be possible to add a toggle for the mouseover function, so that when I'm out of combat and without a target, my player frame remains hidden even when I mouse over it?

I can see code for it in the files, but I've not yet worked out how to disable it myself.

Thank you!

**Comment by joaoc-pires** [comment]
I'm closing this as a duplicate of the other request. We can discuss implementation on that thread
