### ISSUE TITLE
[Feature Request] Always player frame when in group/raid

### ISSUE THREAD

**Issue by Lunaeria** [joaoc-pires/wow-addon-conceal#7]
I swapped to Conceal as the addon I was using for a similar functionality is now defunct. So far, Conceal offers almost everything I need, except... my UI is currently set up in such a way that when I am in a group or raid, the Player Frame should always be shown. With Conceal, if I am out of combat or don't have a target, it gets hidden. 

I was wondering if it would be possible to add a toggle of some sort for the player frame to always be shown in a group or raid, overriding the other combat/target conditions.

**Comment by joaoc-pires** [comment]
This is something that I'll be working on. No promisses, though.

**Comment by joaoc-pires** [comment]
Settings are already as complicated as I feel confortable implementing. Unfortunatly I won't implement this, sorry.
