### ISSUE TITLE
[Feature Request] Hide buffs and pets

### ISSUE THREAD

**Issue by luiscarlos92** [joaoc-pires/wow-addon-conceal#9]
Hi! 
With your great addon I could finally go back to a clean screen as I had in my previous UI pack (RealUI).
There's only to things that still show up that I would like to ask if you could add the option to hide: the buff bar (and debuffs as well) and the pet frame. Right now my screen looks like this (which is already 99% better than the default of having everything on all the time):
![image](https://user-images.githubusercontent.com/8185569/202856219-d96a8b9b-5fa1-4a3e-ae7d-aac559dd9e77.png)

Thank you so much, keep up the great work!

**Comment by joaoc-pires** [comment]
Hey @luiscarlos92. The pet frame should concealed as well. I can't reproduce what you did. Did you manage to uncople the Pet Frame from the Player Frame?

**Comment by joaoc-pires** [comment]
I'm leaving this request open, just to be sure what you got wasn't a bug, but a workaround for the Pet Frame and the Buffs and Bebuffs request will be release in v1.5.0
